platform:ios, '9.0'

target "TeamTalk" do
pod 'FMDB', '~> 2.3'
pod 'SDWebImage', '~> 3.6'
pod 'AFNetworking', '~> 2.3.0'
pod 'DACircularProgress', '~> 2.2.0'
pod 'MBProgressHUD', '~> 0.8'
pod 'PSTCollectionView', '~> 1.2.1'
pod 'HPGrowingTextView' , '~> 1.1'
pod 'ProtocolBuffers', '~> 1.9.4'
pod 'SCLAlertView-Objective-C', '~> 0.7.3'
pod 'MWPhotoBrowser'
pod 'Masonry'
pod 'TTTAttributedLabel'
pod 'SVWebViewController'
pod 'XHImageViewer'
pod 'ZXingObjC'
pod 'Fabric', '~> 1.6.7'
pod 'Crashlytics', '~> 3.7.0'
end
